### ISSUE TITLE
Possibility to add only platform-specific strings to descriptor

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/apm#102]
Hi!

Currently our game have there platform-specific projects: iOS, Android and Amazon.
Projects on each platform have different lists of ANEs inside. 
So it would be nice to have some `platform` argument in `apm init` to keep descriptor clean and do not download redundant ANEs on `install` stage.
For example, now we have about 130 strings in descriptor for iOS, 550+ for Android and 450+ for Amazon.
And it feels dirty when iOS project has much more Android strings the iOS ones.

**Comment by marchbold** [comment]
We are currently investigating options regarding separating platforms etc. 

What exactly would you see as the important part here? Are you just looking to keep the manifest / info additions out of separate app descriptors?

**Comment by sjabberwocky** [comment]
I am looking to:
1. Do not download and include ANEs, which are not related to selected platform. For example, android support for iOS.
2. Generate only platform-specific part for selected platform. `<iPhone>` for iOS only and `<android>` for Android/Amazon only.

**Comment by marchbold** [comment]
The first one is under consideration currently. There's a lot to consider around this so we are working through ideas on how to best implement it. 

The second one is already available, through the `--exclude-ios` and `--exclude-android` options:

```
apm generate app-descriptor

generate an application descriptor with all package required additions

apm generate app-descriptor             generates an application descriptor to 'src/APPNAME-app.xml'
apm generate app-descriptor [out.xml]   generates an application descriptor updating the specified out.xml file

options:
  --exclude-android    excludes generation of the android manifest additions
  --exclude-ios        excludes generation of the iOS info additions and entitlements
``` 

eg:

```
apm generate app-descriptor src/MyApp-app.xml --exclude-ios
```

**Comment by sjabberwocky** [comment]
Hi @marchbold.
When using an Android project, is there a way to avoid creating iOS resource folders?

Currently `assets/ios` and `assets/ios_simulator` folders are created for Android project when I use One Signal ANE, is it possible to not create them?
