### ISSUE TITLE
apm stopped working. Package Updates Available (0)

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#105]
Hello, the apm suddently stopped working. When I try to run `apm update`, it outputs `Package Updates Available (0) (empty)`
Running `apm update apm` outputs the same thing.
p.s. `apm -v` not only prints apm's version, but also npm,node,python etc.

**Comment by marchbold** [comment]
Something sounds very odd there. `apm -v` shouldn't print version information for npm/node/python. They have nothing to do with apm? 

Sounds like something has been installed over the top of apm, can you confirm which apm script you are calling and that it contains the correct contents.

**Comment by jimmymjing** [comment]
I figured it out. Apparently it is calling Atom's apm... I just recently installed Atom.

**Comment by marchbold** [comment]
Bugger, I thought I searched pretty widely for the usage of `apm`, obviously not far enough. 

You can change the name of the `apm` script if you need to avoid the conflict.
