### ISSUE TITLE
How to re edit Package Name in XML with APM

### ISSUE THREAD

**Issue by NathanFitchett** [airsdk/apm#109]
Hey guys so it's a simple question I can't seem to find the cmd line to edit my descriptor file package name I thought i filled out the information correctly however It is adding double the 'air' name in the package xml as shown:

`<provider android:name="androidx.startup.InitializationProvider" android:authorities="air.air.StackCats.androidx-startup" android:exported="false">`

So I have to go through the xml and delete the extra 'air' on the lines that contain the package name.

**Comment by marchbold** [comment]
Did you put an air prefix in your application identifier in the project config? 

apm will automatically prepend this based on the settings for the no flair on your system so you should set the identifier in the config to be the same as your application identifier in your existing application.

**Comment by NathanFitchett** [comment]
Yes I added the Air prefix. Okay So I just need to run "apm init" and run as new project and start fresh but leave out the "air." got it.

**Comment by marchbold** [comment]
Or you can just edit the projact.apm file, it's just a text file so open it in your favourite editor.

**Comment by NathanFitchett** [comment]
Oh okay. Sorry dumb question where can I locate the
