### ISSUE TITLE
Descriptor don't merge due com.distriqt.PushNotifications-OneSignal missed tools schema

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/apm#146]
One Signal is missed `tools` schema (`xmlns:tools="http://schemas.android.com/tools"`) and can not be merged with others ANEs.

**Comment by marchbold** [comment]
Can you give me some more information around how to replicate this? Do you have a custom configuration manifest for your project?

**Comment by sjabberwocky** [comment]
You just need to fix `AndroidManifest.xml` at `apm_packages\com.distriqt.PushNotifications-OneSignal\contents\platforms\android`.

**Comment by marchbold** [comment]
Ah okay, let me have a look into that.

I'll move this issue to the push notifications repository then.

**Comment by marchbold** [comment]
This should be resolved in v11.1.1 of the push notifications ANE. Thanks for reporting this one.
