### ISSUE TITLE
Android can't merge after 1.1.7 update

### ISSUE THREAD

**Issue by leossmith** [airsdk/apm#147]
After updating to 1.1.7 for apm I get the following error when trying to generate app-descriptor:

`✗ Android manifest merge  
generate/app-descriptor :: Error: Exception while merging manifests
Error: org.xml.sax.SAXParseException; lineNumber: 67; columnNumber: 89; The prefix "tools" for attribute "tools:node" associated with an element type "service" is not bound.
`

**Comment by marchbold** [comment]
Nothing was changed around the manifest merging lately. Could you let me know what extensions you are using and if you have any custom configuration files?

**Comment by marchbold** [comment]
This might be related to #146, could you try the update of push notifications onesignal airpackage we have just released.

**Comment by leossmith** [comment]
That did the trick, it was an issue with onesignal. Thank you.
