### ISSUE TITLE
How to run from source?

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#15]
How to run from source?

**Short answer**

1. Run `ant bootstrap`
2. Run `ant build`
3. Use `apm` located into `client/out`

---

Trying to run the tools from the git repo, it doesn't detect my project configuration file:

```sh
# cloned repository, can't run
$ ~/github/apm/client/src/apm help
initial content not found

# installed from releases, it will run
$ ~/tools/apm/apm help
apm <command>
...
```

**Comment by marchbold** [comment]
The source doesn't contain a compiled version of the code. You need to compile it to be able to run from the source. 

I need to get documentation together for this, but there is an ant build script in there as a starting point.

**Comment by j3k0** [comment]
Saw it, I tried `ant build` but it fails.

```
verity:apm jeko$ ant
Buildfile: /Users/jeko/Documents/github/apm/build.xml
  [taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

version_write:

BUILD FAILED
/Users/jeko/Documents/github/apm/build.xml:50: Problem: failed to create task or type var
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.


Total time: 0 seconds


verity:apm jeko$ ant -version
Apache Ant(TM) version 1.10.9 compiled on September 27 2020
```

**Comment by j3k0** [comment]
Note, I edited `build.config` to point to the latest AIR SDK on my computer.

**Comment by j3k0** [comment]
I'm wondering if `net/sf/antcontrib/antlib.xml` isn't missing from the repository?

**Comment by j3k0** [comment]
That was it: the file is downloaded by doing `ant bootstrap`. I got a build successful after that 🥳

**Comment by marchbold** [comment]
Yeah you need to run the bootstrap to setup the env. Will put that in some build docs when i get to them.
