### ISSUE TITLE
update versionNumber

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#151]
Hello, what is the proper way to update the versionNumber? Thanks!

**Comment by marchbold** [comment]
Are you talking about the one that apm injects into your app descriptor with the generate app-descriptor command? 

This is taken directly from the value in the  `project.apm` file.

**Comment by jimmymjing** [comment]
Thanks! I will directly change the version value in the apm file then! I just want to confirm that's the correct way to do so:D

**Comment by marchbold** [comment]
Yeah, we are looking into fleshing out more of the xml settings through apm but haven't done so as yet.
