### ISSUE TITLE
 No package found matching : com.distriqt.admob.IronSource@latest ✗ 

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#153]
Hello,
Everything worked fine but suddenly when I calll `apm update` I got the error message:
```
 No package found matching : com.distriqt.admob.IronSource@latest
✗ No package found matching : com.distriqt.IDFA@latest
```

Basically all packages are not found.

**Comment by marchbold** [comment]
Seems something happened with the repository server. It's back up now, so let me know if you have any further issues.

**Comment by jimmymjing** [comment]
The server issue has been solved. Thanks so much! btw, I do have another issue with `apm`. Sometimes when a package needs update when I called `apm update`, the package firstly gets removed. But sometimes when my computer lost connections with the apm repo server in the middle of updating packages. And then I find these packages are all gone... I have to manually check all anes and see which one gets removed. Is there a way to fix this? Thanks.

**Comment by marchbold** [comment]
Hmmm, yeah i am aware of this little quirk, and i have it on my list to redo the way that works. Just need to find some time to rewrite it :|

**Comment by bsw** [comment]
> Seems something happened with the repository server. It's back up now, so let me know if you have any further issues.

@marchbold can you please have a look if this happens again.

Currently I get:
```
apm search IDFA
✗ Search complete
error connecting to repository server
```

**Comment by marchbold** [comment]
Thanks for letting me know, I'll have to track down whatever is happening on the server.
