### ISSUE TITLE
Can't install any package E::ProcessQueue::Error #3003

### ISSUE THREAD

**Issue by OneHalf3544c** [airsdk/apm#154]
Hello. I'm just trying to get started with the utility.  And most likely I'm doing something wrong, but I can't figure out what exactly is wrong.

Firstly I also have a conflict with atom apm, and I have to use the full path.
I manage to initialize the project and I get the project.apm file.
But I have problems installing any package, both in a new project and an existing one.
files are downloaded to the apm_packages folder, but everything ends with an error E::ProcessQueue::Error #3003
I use Windiws 8.1 os

what could be wrong?

![2022-08-17_8-22-05](https://user-images.githubusercontent.com/5443735/185043612-804eee90-1b71-44aa-90e5-07388c62ebcb.jpg)
![2022-08-17_8-15-35](https://user-images.githubusercontent.com/5443735/185043618-e63454ce-0908-4c9c-8532-9ce72845b7fb.jpg)
![2022-08-17_8-06-38](https://user-images.githubusercontent.com/5443735/185043622-fef469b7-2739-41c7-a4d0-f3f34f01f553.jpg)
![2022-08-17_8-05-56](https://user-images.githubusercontent.com/5443735/185043625-65e689c7-5c5e-4e02-9a68-0a81b3266f86.jpg)

**Comment by marchbold** [comment]
Right, I don't actually have a windows 8 box any more so haven't tested there. 

Could you run it with debug logs:

```
apm -l d ...
```

and post the output. 

Also do you have access to Windows Terminal or a command prompt that supports escape characters? Will make the utility output look a lot nicer.

**Comment by OneHalf3544c** [comment]
apm -l d ...

![2022-08-17_9-08-57](https://user-images.githubusercontent.com/5443735/185046979-718727c2-8f9b-4a01-b8ab-54895d6ae607.jpg)

**Comment by OneHalf3544c** [comment]
Ok, I checked on windows 10 and everything works well there, I will work using windows 10

**Comment by marchbold** [comment]
Hi, sorry the `...` were meant to meant the rest of your install command. 

```
apm -l d install com.distriqt.Core
```

or whatever you were running.

**Comment by OneHalf3544c** [comment]
Hi, Ok, thak you.
I was check this.
[txt.log](https://github.com/airsdk/apm/files/9374045/txt.log)

**Comment by marchbold** [comment]
Ah right, the zip extraction powershell command isn't available on windows 8 by the looks of it. I should be able to get around that by falling back to an as3 implementation. 

Will leave this one open to get it implemented. 

Would you be available to test an update when I have something available?

**Comment by marchbold** [comment]
Could you try this update for me: 
[apm_1.1.8.zip](https://github.com/airsdk/apm/files/9378786/apm_1.1.8.zip)

**Comment by OneHalf3544c** [comment]
> Could you try this update for me: [apm_1.1.8.zip](https://github.com/airsdk/apm/files/9378786/apm_1.1.8.zip)

thanks, it seems to be working now

**Comment by marchbold** [comment]
Great! thanks for confirming, I'll get this rolled into the next release.

**Comment by marchbold** [comment]
Will leave this open until we roll out the update, should be this week.
