### ISSUE TITLE
Can't install com.distriqt.ironsource.AdMob Conflict

### ISSUE THREAD

**Issue by OneHalf3544c** [airsdk/apm#155]
Hi, i have problem with com.distriqt.ironsource.AdMob installation

⣾ Finding package : com.distriqt.ironsource.AdMob@latest
✓ Found package: com.distriqt.ironsource.AdMob@1.0.112
⣽ Finding package : com.google.guava@31.0.x
✓ Found package: com.google.guava@31.0.101
⣻ Finding package : com.distriqt.IronSource@3.3.x
✓ Found package: com.distriqt.IronSource@3.3.1
⢿ Finding package : com.distriqt.playservices.Base@18.0.x
✓ Found package: com.distriqt.playservices.Base@18.0.101
⡿ Finding package : com.distriqt.playservices.Ads@20.5.x
✓ Found package: com.distriqt.playservices.Ads@20.5.1
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.playservices.Ads
CONFLICT :: ├── 21.0.0 required by: com.distriqt.IronSource@3.4.0
CONFLICT :: └── 20.5.1 required by: com.distriqt.IronSource@3.3.1
install ::

Have I can resolve this?

**Comment by marchbold** [comment]
You can use the old version of ironsource until i have time to update the mediators.

https://github.com/distriqt/ANE-IronSource/issues/32

```
apm install com.distriqt.IronSource 3.3.1
```

**Comment by OneHalf3544c** [comment]
thanks, but it still conflict
[txt.log](https://github.com/airsdk/apm/files/9381607/txt.log)
[project.apm.txt](https://github.com/airsdk/apm/files/9381615/project.apm.txt)

**Comment by marchbold** [comment]
You need to uninstall ironsource first, and then install the older version .

**Comment by aclipski** [comment]
I've tried uninstalling Ironsource (`apm uninstall com.distriqt.IronSource`), then installing the old version (`apm install com.distriqt.IronSource 3.3.1`). `apm list` shows 3.3.1 is installed:
```

├──com.distriqt.Notifications@6.3.1
├──com.distriqt.facebook.Core@10.2.1
├──com.distriqt.AppleSignIn@2.2.94
├──com.distriqt.IDFA@5.1.0
├──com.distriqt.facebook.Login@10.2.1
├──com.distriqt.InAppBilling@13.2.4
└──com.distriqt.IronSource@3.3.1

```
Installing Admob after that (apm install com.distriqt. still has the exact same output as before:

```
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.playservices.Ads
CONFLICT :: ├── 21.0.0 required by: com.distriqt.IronSource@3.4.0
CONFLICT :: └── 20.5.1 required by: com.distriqt.IronSource@3.3.1
```

I've also tried installing an older version of Admob (`apm install com.distriqt.ironsource.AdMob 1.0.111`), and it complains about a different conflict:

```
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.playservices.Base
CONFLICT :: ├── 18.0.101 required by: com.distriqt.IDFA@5.1.0
CONFLICT :: └── 17.5.1 required by: com.distriqt.IronSource@3.2.3

``` 

I'm not sure what else to try, it seems impossible to install Admob using apm at the moment.

**Comment by marchbold** [comment]
You'd need to downgrade any extensions that are using play services, so yes IDFA as well. 

Update is coming this week, so probably just worth waiting a few days.
