### ISSUE TITLE
Different build configurations for similar apps

### ISSUE THREAD

**Issue by Kelsonk** [airsdk/apm#157]
I have several similar apps that all use the same ANEs. It would be nice to have different build configurations that can replace the default one, each having it's own package name, version number, and any parameter changes needed for the ANEs (different advertising ids, etc)

**Comment by marchbold** [comment]
Okay, so the parameters for the extensions are possible currently through "build types".

I'll look into adding the ability to change the identifier and version number through these as well.

**Comment by Kelsonk** [comment]
Sorry, trying to find documentation on 'build types'. I essentially just want a new config file with new project config parameters, version, identifier, etc, without having to install all the anes again in a separate folder.

**Comment by marchbold** [comment]
Hi, 

It's a bit manual at the moment, but I've added the ability to set an identifier inside the build types, eg:

```json
"buildTypes": {
        "debug": {
            "identifier": "com.app.debug",
            "configuration": {
                "someparam": "somevalue",
            }
        }
    },
```

I might reopen this one though as I see you have asked for the version as well which currently isn't supported.

**Comment by marchbold** [comment]
FYI: https://github.com/airsdk/apm/wiki/Usage-ProjectsAndPackages#project-parameters
