### ISSUE TITLE
APM project as template generator

### ISSUE THREAD

**Issue by spielepalast** [airsdk/apm#160]
We would like to use APM configuration to generate templates. It works already for most properties except for boolean values.
For example the following is not generated in the output manifest due to the non boolean value `[GET_TASK_ALLOW]`:   

```json
"getTaskAllow": {
            "name": "getTaskAllow",
            "required": "true",
            "value": "[GET_TASK_ALLOW]"
 },
```

**Comment by marchbold** [comment]
Can you elaborate some more for me?

**Comment by spielepalast** [comment]
This would work:

```json
"getTaskAllow": {
            "name": "getTaskAllow",
            "required": "true",
            "value": "false"
 }
 ```
 but this is not working:
 
 ```json
"getTaskAllow": {
            "name": "getTaskAllow",
            "required": "true",
            "value": "AbcXYZ"
 },
 ```

**Comment by marchbold** [comment]
What is the need for this though? We do use some of these values to determine what fields should be used, as some values aren't allowed in app store releases based on flags like this. So they sort of need to be valid for the info additions generation to correctly generate the app descriptor.

**Comment by spielepalast** [comment]
> they sort of need to be valid for the info additions generation

Well, then there is not much that can be done. The need for this came down from using APM to generate an app descriptor that can be processed again to modify some values "on the fly", without re-generating it.
