### ISSUE TITLE
APM giving me errors

### ISSUE THREAD

**Issue by leossmith** [airsdk/apm#163]
I have been trying to update an old project the whole day without any luck (actually ended up in app just crashing on start.

I tried deleting all anes and redownloading but I get random errors like: 

E::ProcessQueue::Error #3012
ERROR :: Failed to install package : androidx.appcompat@1.4.101
install :: Error #3012

or another error of 2032 ( i hate 2032). Any ideas? I am on latest apm.

**Comment by marchbold** [comment]
Is there any more output from the logging with `-l d` in the command?

Try clearing the cache, by deleting the apm_packages and package lock file.

**Comment by leossmith** [comment]
I deleted the ane folder, apm_packages and then package lock. It seemed to work, however I got a lot of errors trying things all day long. From package not found (tried to install previous versions) to failing to install.

Not sure if this is an issue with connection or server load at the time or something. I was able to install the packages after a lot of invalidate cache and deletions. But at that point I started having other issues with packages as I have described in the packages repos. (had to delete http3, then restored it cause it led to firebase crash, then got your push notifications update from a zip file in the repo instead of apm)

**Comment by marchbold** [comment]
Okay, next time you have issues if you could run it with the debug outputs and post it here I'll have a look into it. We do have some fixes coming to resolve issues with failed downloads in cache which seem to break apm in certain circumstances.
