### ISSUE TITLE
CONFLICT :: fatal error : found [1] conflicting packages

### ISSUE THREAD

**Issue by httpwebmedia** [airsdk/apm#166]
⣷ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.0.0
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.0 required by: com.distriqt.PushNotifications-FCM@11.3.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.7

I'm often getting these kinds of issues (conflictings). It's kind of hard to trouble shoot. 
From my understanding, the apm doesn't know which version of Core to install (7.0.0 or 6.4.8) so I should install from PushNotification-FCM the one that use the Core version 6.4.8 right?

Is there a command to get that info so this way I know what version to install for PushNotification?

**Comment by marchbold** [comment]
This is correct.

We are in process of updating all our extensions to the latest AIR SDK features and the new ones are incompatible with older versions.

You should roll back to the previous release until we have finished this rollout.

**Comment by httpwebmedia** [comment]
Ok but could you please answer this "Is there a command to get that info so this way I know what version to install for PushNotification?"

**Comment by httpwebmedia** [comment]
Now I'm getting that issue on a different app...
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.0 required by: com.distriqt.playservices.AppSet@16.0.201
CONFLICT :: └── 6.4.8 required by: com.distriqt.IDFA@5.1.0

AppSet has only one version so I'm stuck here I can't update the app

**Comment by httpwebmedia** [comment]
It's pretty weird it's kind of broken these days I never struggled that much

Installed package : com.google.code.gson@2.8.601
✓ Deployed: androidx.appcompat@1.4.101
✓ Deployed: androidx.browser@1.3.1
✓ Deployed: androidx.constraintlayout@2.1.301
✓ Deployed: androidx.core@1.6.2
✓ Deployed: androidx.room@2.3.1
✓ Deployed: androidx.vectordrawable@1.1.1
✓ Deployed: androidx.work@2.7.1
✓ Deployed: com.distriqt.Adverts@13.7.4
✓ Deployed: com.distriqt.AppGroupDefaults@4.1.68
✓ Deployed: com.distriqt.ApplicationRater@6.1.3
⣾ Deploying package: com.distriqt.Core@6.4.8
E::ProcessQueue::Error #3012
install :: Error #3012

**Comment by marchbold** [comment]
Hmm that issue looks odd.

Can you run apm with debugging outputs and post the output for me:

```
apm -l d install
```

**Comment by httpwebmedia** [comment]
I had to install from a working project and overwrite all files manually myself. It's not the first time I got the error ProcessQueue. I will do it next time I get that issue and report it. Meanwhile, now I got issue with NetworkInfo and Core.ane. Could you update NetworkInfo soon please?

**Comment by httpwebmedia** [comment]
Here is what happening with one app:

CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.0 required by: com.distriqt.Adverts@13.8.1
CONFLICT :: └── 6.4.8 required by: com.distriqt.IDFA@5.1.0
install :: 
⣾ Finding package : com.distriqt.Image@latest
✓ Found package: com.distriqt.Image@5.1.82   
⣽ Finding package : androidx.core@1.x.x
✓ Found package: androidx.core@1.6.2   
⣻ Finding package : com.distriqt.Core@6.x.x
✓ Found package: com.distriqt.Core@6.4.8   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.0 required by: com.distriqt.Adverts@13.8.1
CONFLICT :: └── 6.4.8 required by: com.distriqt.Image@5.1.82
install :: 
⣾ Finding package : com.distriqt.NetworkInfo@latest
✓ Found package: com.distriqt.NetworkInfo@4.0.12   
⣽ Finding package : com.distriqt.Core@6.x.x
✓ Found package: com.distriqt.Core@6.4.8   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.0 required by: com.distriqt.Adverts@13.8.1
CONFLICT :: └── 6.4.8 required by: com.distriqt.NetworkInfo@4.0.12

So NetworkInfo, Image and IDFA are outdated.

**Comment by httpwebmedia** [comment]
Okay forget it it was an issue on my end I mistyped the adverts version I was typing through my script the version 17.7.4 instead of 13.7.4....

I'm waiting for the updates! Thank

**Comment by marchbold** [comment]
If you could drop an issue in the extensions that are blocking you we'll prioritise their updates

**Comment by marchbold** [comment]
And yes I think I'll look into adding a command to apm that tries to find a version that is compatible. Will add that to my to-do list

**Comment by httpwebmedia** [comment]
> If you could drop an issue in the extensions that are blocking you we'll prioritise their updates

I will give it a try today and let you know thank you!

**Comment by httpwebmedia** [comment]
I would need you to update :
NetworkInfo ANE please
This is the last issue I think .

**Comment by httpwebmedia** [comment]
I'm sorry but now for another app we need you to update InAppBilling!! 
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.1 required by: com.distriqt.Adverts@13.8.1
CONFLICT :: └── 6.4.8 required by: com.distriqt.InAppBilling@14.0.2

**Comment by httpwebmedia** [comment]
Okay I tried once more with all latest ANE I needed and here is the output from apm -l d install

`✓ extracted
Installed package : io.reactivex@2.0.201
✓ Deployed: androidx.appcompat@1.4.101
✓ Deployed: androidx.browser@1.4.0
✓ Deployed: androidx.cardview@1.0.1
✓ Deployed: androidx.constraintlayout@2.1.301
✓ Deployed: androidx.core@1.6.2
✓ Deployed: androidx.exifinterface@1.3.301
✓ Deployed: androidx.room@2.3.1
✓ Deployed: androidx.vectordrawable@1.1.1
✓ Deployed: androidx.work@2.7.1
✓ Deployed: com.bumptech.glide@4.12.1
✓ Deployed: com.distriqt.Adverts@13.8.1
✓ Deployed: com.distriqt.AppGroupDefaults@4.2.0
⢿ Deploying package: com.distriqt.ApplicationRater@6.3.0
D::ProcessQueue::UNHANDLED PROCESS ERROR IN com.apm.client.commands.packages.processes::InstallDeployProcess
E::ProcessQueue::Error #3012
E::ProcessQueue::Error: Error #3012
        at com.apm.utils::FileUtils$/copyDirectoryTo()
        at com.apm.client.commands.packages.processes::InstallDeployProcess/start()
        at com.apm.client.processes::ProcessQueue/checkAndStartNextProcess()
        at com.apm.client.processes::ProcessQueue/process_eventHandler()
        at flash.events::EventDispatcher/dispatchEvent()
        at com.apm.client.processes::ProcessBase/complete()
        at com.apm.client.commands.packages.processes::InstallPackageProcess/complete()
        at Function/InstallPackageProcess.as$1:anonymous()
        at com.apm.client.processes::ProcessQueue/checkAndStartNextProcess()
        at com.apm.client.processes::ProcessQueue/process_eventHandler()
        at flash.events::EventDispatcher/dispatchEvent()
        at com.apm.client.processes::ProcessBase/complete()
        at com.apm.client.processes::ProcessBase/complete()
        at com.apm.client.processes.generic::ExtractZipWindowsProcess/onExit()
install :: Error #3012`

**Comment by httpwebmedia** [comment]
Also MediaPlayer needs to be updated...thank you
