### ISSUE TITLE
minsdkversion too high for old phones?

### ISSUE THREAD

**Issue by yvant** [airsdk/apm#175]
Hi, 

Recently, the minSdkVersion and the targetSdkVersion have been updated to 21 and 33 when generating the app.xml with APM, while I was using 19 and 31 to make my app work on an old test phone, using Android 4.4.4.

When I use the generated app.xml, with 31 and 33 as a requirement, then my app cannot be installed on the old phone anymore. So I still use the old app.xml, with the old ANEs (something like 2 months old).

Is there a workaround for this?

**Comment by marchbold** [comment]
This isn't an issue with APM, one of the extensions (or libraries/sdks packaged with the extension) you are using will have a minimum version set to 21. APM uses all your extensions (and libraries) to determine the lowest possible minimum version.

What extensions are you using? 

BTW distriqt is slowly removing support for android 4.x (i.e. api 19), supporting this very old version of android requires too much work and it's generally accepted in the android community that the minimum version should be 21 or 23 currently.

**Comment by yvant** [comment]
Right, this isn't an issue with APM, I didn't know where to post that question. I was just wondering how "fast" the minimum version would progress to see which phone to acquire in order to test armv7 builds, since I had some issues with them recently.

**Comment by marchbold** [comment]
Sure, generally distriqt's extensions just keep up with the current standard. We have been on 19 for around 2 years or so and are migrating to 21 now. Generally it's the underlying SDKs that make this change which results in us updating as well, so hard to predict across the board. 

If you are looking to acquire an old device for testing I'd suggest anything that can run 21 (android 5) is a good old device to use currently, but worthwhile to get one that could be updated a few iterations and that you can install factory android builds on so you can change version easily (eg the nexus and pixel devices - https://developers.google.com/android/images - like a nexus 6 can do from 5.0 through to 7.1).

Also remember there are device emulators in Android Studio and lots of testing platforms that you can use.

**Comment by yvant** [comment]
Thanks for the detailled answer! Indeed, I did not think about emulators, I'll look into it.
