### ISSUE TITLE
APM conflicts with Core Ane

### ISSUE THREAD

**Issue by httpwebmedia** [airsdk/apm#178]
On windows 11
AIRSDK version 50.2.2.6
Java 11
apm 1.2.0

I attempted to use apm and it has been a while (about 3 months ago) but I still have issues using it  : 

⣾ Finding package : com.distriqt.Application@latest
✓ Found package: com.distriqt.Application@6.12.0   
⣽ Finding package : com.distriqt.playservices.Base@18.0.x
✓ Found package: com.distriqt.playservices.Base@18.0.101 
⣻ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
⢿ Finding package : com.distriqt.playservices.AppSet@16.1.x
✓ Found package: com.distriqt.playservices.AppSet@16.1.201 
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.Application@6.12.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
⣾ Finding package : com.distriqt.Adverts@latest
✓ Found package: com.distriqt.Adverts@14.0.3   
⣽ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
⣻ Finding package : com.distriqt.playservices.Ads@21.3.x
✓ Found package: com.distriqt.playservices.Ads@21.3.0   
⢿ Finding package : com.distriqt.playservices.AppSet@16.1.x
✓ Found package: com.distriqt.playservices.AppSet@16.1.201 
⡿ Finding package : androidx.core@1.9.x
✓ Found package: androidx.core@1.9.1   
⣟ Finding package : androidx.appcompat@1.6.x
✓ Found package: androidx.appcompat@1.6.100 
⣯ Finding package : androidx.browser@1.5.x
✓ Found package: androidx.browser@1.5.0   
⣷ Finding package : androidx.room@2.5.x
✓ Found package: androidx.room@2.5.100 
⣾ Finding package : androidx.work@2.8.x
✓ Found package: androidx.work@2.8.100 
⣽ Finding package : com.distriqt.playservices.Base@18.0.x
✓ Found package: com.distriqt.playservices.Base@18.0.101 
⣻ Finding package : com.jetbrains.kotlin@1.8.x
✓ Found package: com.jetbrains.kotlin@1.8.10  
CONFLICT :: fatal error : found [2] conflicting packages
CONFLICT :: com.distriqt.Adverts
E::ProcessQueue::Error #1009
install :: Error #1009
⣾ Finding package : com.distriqt.IDFA@latest
✓ Found package: com.distriqt.IDFA@5.2.0    
⣽ Finding package : com.distriqt.playservices.Base@18.0.x
✓ Found package: com.distriqt.playservices.Base@18.0.101 
⣻ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.IDFA@5.2.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
⣾ Finding package : com.distriqt.Image@latest
✓ Found package: com.distriqt.Image@5.2.0    
⣽ Finding package : androidx.core@1.x.x
✓ Found package: androidx.core@1.9.1   
⣻ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
⢿ Finding package : com.jetbrains.kotlin@1.8.x
✓ Found package: com.jetbrains.kotlin@1.8.10  
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.Image@5.2.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
⣾ Finding package : com.distriqt.NetworkInfo@latest
✓ Found package: com.distriqt.NetworkInfo@4.1.0    
⣽ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.NetworkInfo@4.1.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
⣾ Finding package : com.distriqt.ApplicationRater@latest
✓ Found package: com.distriqt.ApplicationRater@6.3.2    
⣽ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.ApplicationRater@6.3.2
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
⣾ Finding package : com.distriqt.AppGroupDefaults@latest
✓ Found package: com.distriqt.AppGroupDefaults@4.2.0    
⣽ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.AppGroupDefaults@4.2.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
⣾ Finding package : com.distriqt.InAppBilling@latest
✓ Found package: com.distriqt.InAppBilling@14.4.1   
⣽ Finding package : com.google.android.play@1.x.x
✓ Found package: com.google.android.play@1.10.301
⣻ Finding package : com.distriqt.Core@7.x.x
✓ Found package: com.distriqt.Core@7.3.0   
CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.3.0 required by: com.distriqt.InAppBilling@14.4.1
CONFLICT :: └── 6.4.8 required by: com.distriqt.Adverts@13.7.4
install :: 
generate/app-descriptor :: Required package not installed: com.distriqt.Adverts@13.7.4 : run 'apm install'

**Comment by marchbold** [comment]
You need to update your Adverts package as it is old and incompatible with the newer versions of the other extensions. 

What command are you running?

**Comment by marchbold** [comment]
That's odd. Can you start a new issue and include all the details to reproduce this one.
