### ISSUE TITLE
apm android project does not ignore ios_simulator assets folder

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/apm#181]
This is a follow up to https://github.com/airsdk/apm/issues/102.

`apm project set platforms android` does not ignore `assets/ios_simulator` folder for OneSignal ANE.

**Comment by marchbold** [comment]
Ah!! 

Yep will get that fixed... We forgot about the ios simulator platform.

**Comment by marchbold** [comment]
(Just a note too, this is only half implemented as we need to go through the packages and update them with the supported platforms, so you will likely still get androidx libs on ios until we do that).
