### ISSUE TITLE
unable to install anes 

### ISSUE THREAD

**Issue by Shaunmax** [airsdk/apm#182]
apm install com.distriqt.Application
✗ No package found matching : com.distriqt.Application@latest

**Comment by httpwebmedia** [comment]
I'm getting the same issue and when I do "apm search com.distriqt.Adverts" on my end it says  "error connecting to repository server"

**Comment by Shaunmax** [comment]
> I'm getting the same issue and when I do "apm search com.distriqt.Adverts" on my end it says "error connecting to repository server"

seems like apm is down!

**Comment by marchbold** [comment]
Hi, We had an issue when updating the server to support platforms. It should be back up now. Apologies for the inconvenience.

**Comment by httpwebmedia** [comment]
It's back on track. Thank you
