### ISSUE TITLE
Cannot install from project.apm : E::ProcessQueue::SyntaxError: Error #1132         at JSON$/parse()

### ISSUE THREAD

**Issue by shaymolho** [airsdk/apm#189]
I want to rollback to a previous version of project.apm
this is my project.apm i want to install (ane directory empty, project-lock.apm doesn't exist)
[project.apm.zip](https://github.com/airsdk/apm/files/12417418/project.apm.zip)
apm install logs:
[apm-install-error.log](https://github.com/airsdk/apm/files/12417435/apm-install-error.log)

**Comment by marchbold** [comment]
When trying a clean install make sure you delete the `apm_packages` directory, ideally you should keep the lock file from the version you are wanting to rollback to, but a straight `apm install` should work may just pick up some different dependencies.

**Comment by shaymolho** [comment]
I managed without reverting
