### ISSUE TITLE
Github personal access tokens have been removed

### ISSUE THREAD

**Issue by sweetnitro** [airsdk/apm#197]
Hi,

Creating a new issue since not sure commenting on an old closed one will be noticed. 

It seems that since the wiki was written, the authentification system has changed at Github. I don't have access to "Personal Access Tokens" and only GPG or SSH keys are available.

I tried using a GPG key but it does not work (tried ghp_XXX... with both the key id and the subkey value but no format works).

![image](https://github.com/airsdk/apm/assets/46676864/3cbc63fe-ccbd-4b9e-b5fd-0ccf9018b61f)

Thanks for your help

**Comment by marchbold** [comment]
Please navigate all the way to the bottom on that menu:

select "Developer Settings"
/ "Personal Access Tokens"
/ "Tokens classic"

This should be where you can generate the token you need.

**Comment by sweetnitro** [comment]
Thanks @marchbold ... I feel silly for bothering you ! All working fine now :)

**Comment by marchbold** [comment]
Great to hear :)
