### ISSUE TITLE
APM removes user-added additions in <InfoAdditions>

### ISSUE THREAD

**Issue by cleverbeapps** [airsdk/apm#200]
Hi!
First of all, want to thank you for APM. It is so helpful and convenient. 

So, I am trying to add 
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
but each time after  "apm generate app-descriptor" it has been removed. So how to keep it without being removed?
<img width="472" alt="image" src="https://github.com/airsdk/apm/assets/96975636/d6c7c51e-e8a3-4e1e-bb74-2574beaff661">

**Comment by marchbold** [comment]
Run 

`apm generate config ios` 

This will create an `Enttilements.xml` and `InfoAdditions.xml` files in the `config/ios` directory. These will get merged into the app descriptor when you run `apm generate app-descriptor` so add any custom additions you require into there (you should find the template contains some common additions like the storyboard). 

Let me know if that doesn't make sense.

**Comment by marchbold** [comment]
Note: You can do the same for custom android additions

`apm generate config android`

and add any custom android manifest entries to `config/android/AndroidManifest.xml`

**Comment by cleverbeapps** [comment]
Thank you, Michael. It works! 
Also curious, is there any way to permanently set required=false here?
<img width="559" alt="image" src="https://github.com/airsdk/apm/assets/96975636/f55c8cca-6900-4864-bdf4-725e39018a3f">

**Comment by marchbold** [comment]
Ah those values are required though for Google Identity I believe?

**Comment by cleverbeapps** [comment]
Yes, but since I need Google Identity only for sign-in on Android devices, I don't need those iOS configurations. So, it will be great to have these fields not required somehow.

**Comment by marchbold** [comment]
I see, will have to think about that one, we are still working on platform specific outputs from apm but I don't believe we can currently handle an extension that is installed but only used on one platform.

**Comment by cleverbeapps** [comment]
Anyway, thanks! APM helps a lot.
