### ISSUE TITLE
APM error

### ISSUE THREAD

**Issue by Nisaba** [airsdk/apm#202]
Hi,

I've this error when I want to use APM command :

```
Information: Unable to find files for the specified model(s).
Using the path operator in substitution
command parameter is invalid: %~dpa
For valid formats, enter CALL .? or FOR /?
The command syntax is not correct.
```

![image](https://github.com/airsdk/apm/assets/34550856/f723e5b6-0d49-474a-a7e5-191e1bf23aa8)

I've reinstalled APM as described here, wit no success
https://airsdk.dev/docs/basics/install-apm

Please help, thank you !

**Comment by marchbold** [comment]
Could you give me some information about your environment? Not sure where that output is coming from, you don't have another program called `apm` installed do you?

**Comment by Nisaba** [comment]
Yes, ok,
The issue is fixed. Thank you
