### ISSUE TITLE
CONFLICT 

### ISSUE THREAD

**Issue by Shaunmax** [airsdk/apm#203]
Why am I getting this error while updating apm ? 

```
CONFLICT :: fatal error : found [2] conflicting packages
CONFLICT :: com.distriqt.Adverts
CONFLICT :: ├── 15.0.0
CONFLICT :: └── 14.3.0 required by: com.distriqt.admob.AdColony@4.9.5
CONFLICT :: com.distriqt.playservices.Ads
CONFLICT :: ├── 23.0.0 required by: com.distriqt.Adverts@15.0.0
CONFLICT :: └── 22.2.1 required by: com.distriqt.Adverts@14.3.0
```

**Comment by marchbold** [comment]
We are still in progress of updating the mediation adapters for AdMob, in the meantime remove v15 and install v14.3.0

**Comment by Shaunmax** [comment]
> We are still in progress of updating the mediation adapters for AdMob, in the meantime remove v15 and install v14.3.0

Also, was this issue fixed, I can see `com.distriqt.Adverts@15.1.0`  with no conflicts

**Comment by marchbold** [comment]
Yes the adapters were updated: https://github.com/distriqt/ANE-Adverts-Mediation/releases/tag/v7.0.0
