### ISSUE TITLE
Android crash after updating app descriptor and ANEs

### ISSUE THREAD

**Issue by apofis1969** [airsdk/apm#204]
I updated today the ANes and the app descriptor file of my app.
The app crashes completely when opening, because I think that there is a bug in the manifest.
Using the recent manifest no error appears.
Attached I add the new myApp-app.xml file and the error log.
Hopefully you can tell me what is wrong.

Using APM Version: 1.6.4
AIR SDK: 50.2.5.1

[myApp-app.txt](https://github.com/airsdk/apm/files/15273334/myApp-app.txt)
[errorlog.txt](https://github.com/airsdk/apm/files/15273335/errorlog.txt)

**Comment by marchbold** [comment]
Can you post your project and project-lock files?

**Comment by marchbold** [comment]
Hi, Thanks for that, but can you post your apm project and project-lock files?

**Comment by apofis1969** [comment]
Hi, sorry. Understood wrong. Here they are

[project-apm.zip](https://github.com/airsdk/apm/files/15305176/project-apm.zip)

**Comment by marchbold** [comment]
I dont see any issues with your project files. Did you regenerate your app descriptor after updating to ensure your manifest is correct? 

```
apm generate app-descriptor
```

**Comment by apofis1969** [comment]
Hi, yes I did generate a new myApp-app.xml file. The recent I have works. The new crashes the app completely. 
I did:
apm generate app-descriptor MyApp-app.xml

**Comment by apofis1969** [comment]
Do you mean the apm? It is still 1.6.4 from July 2023

**Comment by marchbold** [comment]
No I mean update the packages.

**Comment by apofis1969** [comment]
Hi, I updated the packages but now I get this error while building the aab file using Sonoma 14.5

`unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:desugarReleaseFileDependencies'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed: ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:desugarReleaseFileDependencies'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

	at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
	at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)`

**Comment by marchbold** [comment]
Try setting your minimum sdk version to 24 

https://github.com/airsdk/Adobe-Runtime-Support/issues/3236

If you are using apm

```
apm generate config android
```

edit the file at `config/android/AndroidManifest.xml` and set the minimum sdk version to be 24, then regenerate your app descriptor.

**Comment by apofis1969** [comment]
Thanks. I forgot to change the minimum version. All working.
