### ISSUE TITLE
Installing APM. zsh: permission denied

### ISSUE THREAD

**Issue by crooksy88** [airsdk/apm#206]
Hi, I'm trying to install APM on MacOS but I'm not getting the version number back when requesting it.
Following the installation instructions I'm up to Verify Installation.

I have downloaded the APM files (4 files) and copied them to a directory.

apm -version
returns...
zsh: permission denied: apm

Any suggestions on how to fix this would be very much appreciated.

Thanks.

Here are the contents of the .zshrc file...

export AIR_HOME=/Applications/AIRSDK/50.2.2.6
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home
export AIR_TOOLS=/Applications/AIRSDK/apm
export PATH="${PATH}":"${AIR_HOME}/bin":"${AIR_TOOLS}"

**Comment by marchbold** [comment]
If you unzipped it manually you may have to change the permissions on the file, try running:

```
chmod 755 $AIR_TOOLS/apm
```

**Comment by crooksy88** [comment]
Wonderful! Thanks Michael.💫

**Comment by crooksy88** [comment]
Could you possibly point me to instructions on how to resolve this please...

how to get and set my github access token

**Comment by marchbold** [comment]
No problems! :)
