### ISSUE TITLE
AndroidManifest.xml manifest merge failed "Missing 'name' key attribute on element activity"

### ISSUE THREAD

**Issue by cleverbeapps** [airsdk/apm#208]
Hi!
I'm trying to implement Digital Asset Links in my Android app. 
I have apm config file:
config/android/AndroidManifest.xml

![screen](https://github.com/user-attachments/assets/478ac931-511c-4269-ad77-478c876601d7)

But when I try to generate a descriptor - I get an error:
"Missing 'name' key attribute on element activity"
How do we merge it properly? Thanks.
@marchbold

**Comment by marchbold** [comment]
Remove the attributes on the activity and it should work. 

```xml
<activity>
   ...
</activity>
```

**Comment by cleverbeapps** [comment]
Michael, thank you, it works now.
