### ISSUE TITLE
Manifest merger never ends.

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#24]
The manifest merger task stays running forever (when run by `apm`)

I need to `CTRL-C` to stop execution, but then the tasks are still running (and accumulate).

`ps aux` showed that I had 8 processes running like this one:

`/usr/bin/java -jar "/Users/jeko/Library/Application Support/airsdk.apm/Local Store/tools/manifest-merger-30.0.1.jar" --main /tmp/xxx/.tmp538437/AndroidManifest.xml --property PACKAGE=air.com.my.app --remove-tools-declarations`

When ran manually, it exits almost immediately and show the result on the console.

It occasionally succeeds though, might it be a race condition?

---

Also, `apm` should make sure it kills it child processes when it is killed.

**Comment by marchbold** [comment]
Can you give me more information on what packages you are using?

**Comment by j3k0** [comment]
No package installed, still testing from the empty project. It's a bit weird, when it happens it would always happen. Now it doesn't happen anymore, didn't anything apart adding some logs... I'll see if I can reproduce.

**Comment by marchbold** [comment]
Hmmm odd... haven't seen that before. What version of java is at /usr/bin/java on your machine?

**Comment by j3k0** [comment]
It version `1.8.0_271`.

This had me thinking and got a little more info: it happens when I set `JAVA_HOME=/usr` 

Run this way it "breaks" (never ends):

`AIR_HOME=~/Fovea_AIR_Toolchains/air-33.1.1.575 JAVA_HOME=/usr ~/Documents/github/apm/client/out/apm generate app-descriptor`

Run this way it works fine:

`AIR_HOME=~/Fovea_AIR_Toolchains/air-33.1.1.575 ~/Documents/github/apm/client/out/apm generate app-descriptor`

(still testing from the empty project)

**Comment by j3k0** [comment]
Strangely enough, when NOT setting JAVA_HOME to anything, I confirmed that `RunConfig::getJava()` returns `/usr/bin/java`...

---

After digging a little bit deeper, I found out that running the manifest-merger process manually this way (adding `JAVA_HOME=/usr`) will make it hang:

`JAVA_HOME=/usr /usr/bin/java -jar "/Users/jeko/Library/Application Support/airsdk.apm/Local Store/tools/manifest-merger-30.0.1.jar" --main /tmp/xxx/.tmp845059/AndroidManifest.xml --property PACKAGE=air.com.my.app --remove-tools-declarations`

So this tool is not happy when JAVA_HOME is set.

**Comment by j3k0** [comment]
More details: I seem to ONLY have the issue when `JAVA_HOME` is set to `/usr`.

When running the manifest-merger manually, I can set it to a valid or invalid location, it will work (except for `/usr`).

When running `apm`, if I set `JAVA_HOME` to something like `/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home`, it goes through.

No idea what's wrong with `JAVA_HOME=/usr`...

I tried to see how to remove this environment variable when running the child process, but it doesn't look that easy (NativeProcess functions doesn't have this kind of parameters).

Alternatively, there could be some logic similar to what you did for windows, to use the latest JVM located in `/Library/Java/JavaVirtualMachines`.

**Comment by j3k0** [comment]
... or use the `java_home` utility, which has an option to return a specific version if available: `/usr/libexec/java_home -v 1.8`

**Comment by j3k0** [comment]
Since this looks more like an issue with `manifest-merger-30.0.1.jar`, I guess it's OK to close here.

**Comment by marchbold** [comment]
Hi, 

This is actually an issue with incorrectly setting `JAVA_HOME` to be `/usr`. `JAVA_HOME` is expected to point to a JDK/JRE installation not just the java executable.  

This causes issues with a lot of java programs, in the update I've removed this as a default and use the `java_home` executable instead. 

If you are still setting it to /usr on the command line I suggest you correct that.

**Comment by j3k0** [comment]
> If you are still setting it to /usr on the command line I suggest you correct that.

I'm not, this was my mistake then.
