### ISSUE TITLE
application descriptor not found

### ISSUE THREAD

**Issue by leossmith** [airsdk/apm#3]
Sorry to create the 1st issue (of course it had to be me 😅 ). Giving it a try in several projects but i get the same "application descriptor not found".

I tried in Flex and Feathers projects (I dont have any pure as3 ones to test) and both in project folder and src.

Edit: On side note i believe this is an issue with apm itself and not the fact it doesnt find the decriptor

**Comment by leossmith** [comment]
Looks like this was an issue on my laptop. Moving to desktop and redo the install works, so never mind.

**Comment by marchbold** [comment]
That error probably indicates it can't find the apm.xml app descriptor which should be alongside the SWF and scripts. Maybe just check the download and zip extraction worked?

**Comment by marchbold** [comment]
just a note , this is really limited right now, we need to populate the  repository with more packages

**Comment by marchbold** [comment]
but would be really keen on any feedback on the setup / usage etc...

**Comment by leossmith** [comment]
Installation process was ok for me, but might be a good idea to make an "installation" archive that automatically sets paths and everything to avoid user error. 

Concerning repo, might be a good idea to have a guide on how people can upload their libs to it.

**Comment by marchbold** [comment]
Yeah we have a section on creating packages here:

https://github.com/airsdk/apm/wiki/Usage-CreatingPackages

This will grow quickly as we expand the functionality.
