### ISSUE TITLE
Publish a private package

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#32]
When publishing a package where the sourceUrl is private (in a private git repo), I get this error: `source url returned 404`

However, I'm able to install packages from private repos (namely those from Distriqt).

The github token is set in the apm config file.

Since I'm publishing into an internal apm repository, I wouldn't mind having an option to disable the `sourceUrl` test.

**Comment by marchbold** [comment]
What is the url you are using? You should use the url to a release asset.

I don't believe disabling the test is a good idea, otherwise you'll end up with invalid packages in the repository.

**Comment by j3k0** [comment]
That's the URL: https://github.com/j3k0/mypackage/releases/download/v1.0.0/cc.fovea.mypackage_1.0.0.airpackage

It works when open from my browser (when I'm logged in with github).

I've added some logs to confirm that `PackageRequestUtils` added the github token to the request.

Here are the logs (some have been added by me).

```
⡿ Checking remote content: https://github.com/j3k0/triplaxe/releases/download/v1.0.0/cc.fovea.mypackage_1.0.0.airpackage
D::PackageRequestUtils::generateURLRequestForPackage( https://github.com/j3k0/mypackage/releases/download/v1.0.0/cc.fovea.mypackage_1.0.0.airpackage ... )
D::PackageRequestUtils::generateURLRequestForPackage(): GITHUB ASSET URL
D::PackageRequestUtils::generateURLRequestForPackage(): calling github API /repos/j3k0/mypackage/releases
⣯ Checking remote content: https://github.com/j3k0/mypackage/releases/download/v1.0.0/cc.fovea.mypackage_1.0.0.airpackage
D::PackageRequestUtils::generateURLRequest(): github token: ghp_EDITED
D::PackageRequestUtils::generateURLRequest(): url: https://github.com/j3k0/mypackage/releases/download/v1.0.0/cc.fovea.mypackage_1.0.0.airpackage
✗ source url returned 404
```

It looks like it didn't rewrite the URL to this form: `"https://api.github.com/repos/" + repo + "/releases/assets/" + asset.id`

**Comment by marchbold** [comment]
Could be related to the access permissions you gave your token?  Might have to be more clear on what's required there. 

We use the github api to retrieve the asset id for a private repository, which is the only way you can directly download it. 

If you want to debug have a look at the `PackageRequestUtils` class and see what the api returns there.

**Comment by j3k0** [comment]
I found the issue in `generateURLRequestForPackage()`.

When looking for the matching release, it's doing:

```js
if (release.name == version)
```

However, in my case I didn't set the `name` to match the `tag_name`. The asset URL in the API uses the `tag_name`. I submitted a PR that fixes this.
