### ISSUE TITLE
Possible abuse to retrieve users github tokens

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#35]
If a package's `sourceUrl` is set to any URL that contains the string `github.com`, the token is attached to the request.

cf: https://github.com/airsdk/apm/blob/1be2921ecc0247dc9e04aabbc8d5e0049e00f688/client/src/com/apm/client/commands/packages/utils/PackageRequestUtils.as#L132

### possible abuse

By setting the `sourceUrl` to: `https://www.evil.com/releases/assets/github.com/package_1.0.0.airpackage`

The publisher / owner of the `evil.com` domain can then collect github tokens from people downloading the package.

### possible solution

Check that the download URL **starts with** `https://api.github.com/`

I'll test this and submit a PR. (Done: #36)

**Comment by marchbold** [comment]
Yep too true.
