### ISSUE TITLE
apm init don't work

### ISSUE THREAD

**Issue by Elintondm** [airsdk/apm#40]
After execute ```apm init``` nothing happens.

![image](https://user-images.githubusercontent.com/21336929/134432737-ba9adca7-dda8-406d-b68c-bff133ade2ac.png)

**Comment by marchbold** [comment]
Does `apm -version` output the version information? 

If it doesn't could you check you followed the installation guide, and post the output from `apm -l d init`.

**Comment by marchbold** [comment]
Is that windows terminal or just a straight ps console? We suggest using windows terminal with powershell as you get much better support for console outputs.

**Comment by Elintondm** [comment]
I'm using Windows Terminal Application from Windows Store. The command apm -version is working fine.

**Comment by marchbold** [comment]
Did you try `apm -l d init`?

**Comment by Elintondm** [comment]
![image](https://user-images.githubusercontent.com/21336929/134574261-a6759ff7-27a8-46b1-bb2a-db302f3a9183.png)

**Comment by marchbold** [comment]
Hmm odd, I'll get some more logging into the next build as to why that load environment process is failing.

Could you check that `cmd /c set` outputs your environment variables?

**Comment by marchbold** [comment]
I've just released v0.0.7, could you confirm you see the same behaviour with the latest release?

**Comment by Elintondm** [comment]
Using v0.0.7:
![image](https://user-images.githubusercontent.com/21336929/134746222-8a5ad38c-06eb-44ae-93b9-47c3fd02aa5d.png)

![image](https://user-images.githubusercontent.com/21336929/134746261-a4432735-b24c-420e-93bd-431c009a584f.png)

![image](https://user-images.githubusercontent.com/21336929/134746279-c2022267-3778-4ad7-a780-cb17922e62d0.png)

**Comment by marchbold** [comment]
Have you cut off the output or is that all there is?

**Comment by Elintondm** [comment]
That is all.

Em dom., 26 de set. de 2021 21:07, Michael ***@***.***>
escreveu:

**Comment by marchbold** [comment]
So there is no version information output at all?

**Comment by Braisor** [comment]
same here windows powershell, apm 1.0.0, adt 33.1.1.674
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
D::RunConfig::loadEnvironment()
D::LoadWindowsEnvironmentVariablesProcess::start()
PS C:\Users\

**Comment by marchbold** [comment]
@Braisor can you give me some details on your environment? Haven't been able to replicate this behaviour yet

**Comment by Braisor** [comment]
Adobe Air.   Free version ! with splashscreen, maybe...  (apm work on my mac with same version). Paid version is coming, new test  too.

Full admin access, nothing special :

Windows 10 Pro
Version	21H1
Build 19043.1237
// 
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
Name             : ConsoleHost
Version          : 5.1.19041.1237
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : fr-FR
CurrentUICulture : fr-FR
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


//  same results with latest Powershell / admin or not

PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
Name             : ConsoleHost
Version          : 7.2.0
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : fr-FR
CurrentUICulture : fr-FR
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace


AIR_HOME=C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirSDK\current
AIR_TOOLS=C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirTools\apm
ALLUSERSPROFILE=C:\ProgramData
AMDRMPATH=C:\Program Files\AMD\RyzenMaster\
AMDRMSDKPATH=C:\Program Files\AMD\RyzenMasterSDK\
APPDATA=C:\Users\alpac\AppData\Roaming
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=132347029731801108
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-9UJILRD
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\alpac
LIBJABRA_TRACE_LEVEL=debug
LOCALAPPDATA=C:\Users\alpac\AppData\Local
LOGONSERVER=\\DESKTOP-9UJILRD
NUMBER_OF_PROCESSORS=24
OneDrive=C:\Users\alpac\OneDrive
OneDriveConsumer=C:\Users\alpac\OneDrive
OS=Windows_NT
Path=C:\Program Files\PowerShell\7;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\WireGuard\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirSDK\current\bin;C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirTools\apm;C:\Program Files\PowerShell\7\;C:\Users\alpac\AppData\Local\Microsoft\WindowsApps;C:\Users\alpac\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\alpac\AppData\Roaming\npm;C:\Users\alpac\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Pro
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
PROCESSOR_LEVEL=23
PROCESSOR_REVISION=7100
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Users\alpac\OneDrive\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\Users\alpac\Documents\WindowsPowerShell\Modules;C:\Users\alpac\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\alpac\AppData\Local\Temp
TMP=C:\Users\alpac\AppData\Local\Temp
USERDOMAIN=DESKTOP-9UJILRD
USERDOMAIN_ROAMINGPROFILE=DESKTOP-9UJILRD
USERNAME=alpac
USERPROFILE=C:\Users\alpac
windir=C:\WINDOWS
WSLENV=WT_SESSION::WT_PROFILE_ID
WT_PROFILE_ID={574e775e-4f2a-5b96-ac1e-a2962a402336}
WT_SESSION=49573af4-330c-4120-a003-3ada535ae63f

Hope this help, let me know if you want more info.

**Comment by marchbold** [comment]
Is there anything unusual about the path you have `apm` in i.e. `C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirTools\apm` ? 

Is that a mapped location or something? Just wondering if it is something to do with a network mapped location?

**Comment by marchbold** [comment]
Bit lost as to what's happening here. Could you try the following build, I've added a lot more outputs:

[apm_1.0.1-test.zip](https://github.com/airsdk/apm/files/7544521/apm_1.0.1-test.zip)

Run it with verbose logging:

```
apm -l v version
```

and let me know the output? 

Do you have an antivirus software or is your user account somehow limited at all? (Just guesses here).

**Comment by Braisor** [comment]
SynologyDrive create folders like Dropbox. Air and apm files are synchronized locally. I tried in another location (except Air)
Windows Admin Account / Only windows defender 

V::Log::setLogLevel( verbose )
D::RunConfig::loadEnvironment()
V::RunConfig::Adding LoadWindowsEnvironmentVariablesProcess
V::RunConfig::Adding LoadWindowsJavaHomeProcess
V::RunConfig::Adding LoadProjectDefinitionProcess
V::RunConfig::Adding LoadUserSettingsProcess
V::RunConfig::load queue start
V::ProcessQueue::checkAndStartNextProcess(): 4
D::LoadWindowsEnvironmentVariablesProcess::start()
V::LoadWindowsEnvironmentVariablesProcess::start(): Get Command Interpretor
V::LoadWindowsEnvironmentVariablesProcess::start(): cmd: C:\WINDOWS\System32\cmd.exe
V::LoadWindowsEnvironmentVariablesProcess::start(): Creating processArgs
V::LoadWindowsEnvironmentVariablesProcess::start(): Creating NativeProcessStartupInfo
V::LoadWindowsEnvironmentVariablesProcess::start(): Creating NativeProcess
V::LoadWindowsEnvironmentVariablesProcess::start(): Starting NativeProcess

**Comment by marchbold** [comment]
Does the app exit or does it stop at that point and you have to terminate it?

**Comment by Braisor** [comment]
exit, immediately or after a few seconds

**Comment by Braisor** [comment]
From windows event viewer :

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-11-16T09:44:05.1822220Z" /> 
  <EventRecordID>73707</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-9UJILRD</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>adl.exe</Data> 
  <Data>33.1.1.674</Data> 
  <Data>61842a4a</Data> 
  <Data>Adobe AIR.dll</Data> 
  <Data>33.1.1.674</Data> 
  <Data>6184339a</Data> 
  <Data>c0000005</Data> 
  <Data>0034ad5b</Data> 
  <Data>3184</Data> 
  <Data>01d7dace7e498ac0</Data> 
  <Data>C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirSDK\current\bin\adl.exe</Data> 
  <Data>C:\Users\alpac\SynologyDrive\alpach\C\Pro\AirSDK\current\runtimes\air\win\Adobe AIR\Versions\1.0\Adobe AIR.dll</Data> 
  <Data>3243107e-21c4-44ac-b941-b8c5cb1a49f7</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by marchbold** [comment]
Oh right, there's an actual AIR error, 

@ajwfrost any idea what would cause this? 

It's happening when we execute the NativeProcess `cmd /c set` call here:

https://github.com/airsdk/apm/blob/master/client/src/com/apm/client/config/processes/LoadWindowsEnvironmentVariablesProcess.as#L64-L86

**Comment by ajwfrost** [comment]
Hi @marchbold @Braisor  - I've just been trying to reproduce this, but it works fine for me:

```
D::LoadWindowsEnvironmentVariablesProcess::start()
V::LoadWindowsEnvironmentVariablesProcess::start(): Get Command Interpretor
V::LoadWindowsEnvironmentVariablesProcess::start(): cmd: C:\WINDOWS\System32\cmd.exe
V::LoadWindowsEnvironmentVariablesProcess::start(): Creating processArgs
V::LoadWindowsEnvironmentVariablesProcess::start(): Creating NativeProcessStartupInfo
V::LoadWindowsEnvironmentVariablesProcess::start(): Creating NativeProcess
V::LoadWindowsEnvironmentVariablesProcess::start(): Starting NativeProcess
D::LoadWindowsEnvironmentVariablesProcess::onClose: (standardOutputClose)[Event type="standardOutputClose" bubbles=false cancelable=false eventPhase=2]
D::LoadWindowsEnvironmentVariablesProcess::onClose: (standardErrorClose)[Event type="standardErrorClose" bubbles=false cancelable=false eventPhase=2]
D::LoadWindowsEnvironmentVariablesProcess::onClose: (standardInputClose)[Event type="standardInputClose" bubbles=false cancelable=false eventPhase=2]
D::LoadWindowsEnvironmentVariablesProcess::Process exited with: 0
V::LoadWindowsEnvironmentVariablesProcess::processEnvironmentVariables(): ADL_DIR=i:\SDKs\33.1.1.674\bin\adl.exe
AIRINSTALL_DEBUG=1
AIR_BIN_DIR=i:\SDKs\33.1.1.674\bin\
AIR_DIR=i:\SDKs\33.1.1.674\
AIR_HOME=i:\SDKs\33.1.1.674
ALLUSERSPROFILE=C:\ProgramData
...
```

I've tried in a normal command prompt and in a command prompt with admin rights, plus in a Powershell console, all on Windows 10. Can I check what OS version and mechanism you were using here? And is it possible to check that event viewer output and capture an image of it, I'm not sure whether that's saying there was an exception in the DLL (`c0000005`?) but it would be good to see the fault address if so - or even better if you can capture a kdmp file from it..?

thanks

**Comment by Braisor** [comment]
Something like this ? 
https://www.dropbox.com/s/ki2izoc4atnchmx/CrashDumps.zip?dl=1

**Comment by ajwfrost** [comment]
@Braisor that's perfect thanks, yes that took us straight to it. Odd that we can't reproduce it because this is just a function that's checking to see if there are Windows messages pending and it's looking at the display lists' native window objects for this. And of course, for command-line tools there are no windows. We missed this one, most of the code has a null-check around it now so we'll add this in...

thanks

**Comment by Braisor** [comment]
Glad to have helped to solve this. And thanks to you for this project :)

**Comment by marchbold** [comment]
Thanks for finding that one @ajwfrost + @Braisor ! I was stumped as all looked to be working perfectly with our tests. 

When do you think you'll be able to update the AIR SDK with this fix?

**Comment by ajwfrost** [comment]
It was such a small fix that I sneaked it in to the build that had already been kicked off :-) so hopefully tonight/tomorrow morning...

**Comment by marchbold** [comment]
Brilliant, thankyou! 

@Braisor will you be able to test with this new release for us to confirm the fix? As I can't replicate hoping you have some time to check for us :)

**Comment by Braisor** [comment]
Sure

**Comment by Braisor** [comment]
AIR 33.1.1.686   ->   apm now works ;)

**Comment by ajwfrost** [comment]
Great thanks for confirming!

**Comment by marchbold** [comment]
@Braisor Thanks for your time on this one!
