### ISSUE TITLE
Project config templating

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#42]
For now, the project configuration allows replacing variables like so:

`${somevar}` gets replaced with `project.configuration.somevar`.

Some thoughts.

### 1. conditionals

If would be nice to be able to some thing like this:

```sh
${ env = "production" ? somevar : someothervar }
```

### 2. application descriptor

Shouldn't the application descriptor be a template too?

### 3. overrides

Instead of modifying the project when building for different targets, allow the project configuration to be overriden with environment variables. I'm preparing PR with this idea. (Done #43)

**Comment by j3k0** [comment]
### 4. add "identifier", "version", "name", "versionLabel"

Adding those root fields to the project configuration will allow to use them in the templates. Could be done quite easily in "config.loadProjectDefinition()" from #43.

**Comment by marchbold** [comment]
I don't think conditionals in the config files are a good idea. 

I'd prefer to see something more standard like build configurations defined in the project file. This is how Android and many other systems handle this process and we have to work within the Android merge system to correctly handle the manifest merge. Placing conditionals in the android manifest will fail so I'd prefer to keep a consistent system in place across all platforms.  

Also I'm not sure the use of the name "template" is right here. I was using that for the application descriptor but that isn't really correct for the ios and android manifest files. These are additional files that are merged into the info additions / entitlements / manifest.
