### ISSUE TITLE
application descriptor fails with attributes indented with tabulation

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#44]
This fails (using the tabulation character to indent XML attributes):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application
	xmlns="http://ns.adobe.com/air/application/18.0"
	minimumPatchLevel="0">
	<id>com.example.app</id>
</application>
```

This works (using space to indent the XML attributes):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<application
 xmlns="http://ns.adobe.com/air/application/18.0"
 minimumPatchLevel="0">
	<id>com.example.app</id>
</application>
```

---

Side note: I improved a tiny bit the application descriptor validation, so it returns the detail of the error (incoming PR). It says: `"<id> tag not found"` when it fails in the above case.

**Comment by j3k0** [comment]
I might have found he issue, some regexp magic in ApplicationDescriptor.loadString() needs fixing.

**Comment by j3k0** [comment]
PR #45 fixes the issue.

**Comment by marchbold** [comment]
I believe it's just the space character there that needs to be removed.
