### ISSUE TITLE
apm install is slow

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#67]
On my setup, `apm install` takes more than 10 minutes to complete, even when all the dependency are already installed. There are approximately 50 packages in `apm_packages`.

If a package with the correct version is already found in the cache, `apm install` should go over it very quickly. For now, it looks like it's checking with the server and re-extracting it.

---

Iterating is very time consuming, when debugging stuff like https://github.com/distriqt/ANE-Firebase/issues/387

It also makes CI builds very slow, because they have to run `apm install`, just in case a new dependency has been added.

**Comment by marchbold** [comment]
Resolved in v1.1.1. We have introduced a lock file which means it will only query the server for an install call if new packages are installed.
