### ISSUE TITLE
apm install failing silently

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#71]
During `apm install`, downloading one of the dependencies did timeout.

However `apm` went on to the end without reporting an error: except a `x` symbol next to the package name when it tried downloading. The package wasn't installed, so the next steps in the build chain failed.

`apm install` should keep a log of errors when doing `apm install`, display them at the end of the process and exit with a non-zero code if there where any.

**Comment by marchbold** [comment]
The `invocation forwarded to primary instance` issue has been resolved in the latest AIR and apm releases. 

I'm going to close out this issue as I believe it was likely related to either that or the other launch issues related to adl that were solved in an earlier release of AIR. 

But if you can replicate it please let me know.

Cheers
