### ISSUE TITLE
stuck on the phase "extracting airpackage"

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#82]
Hello, I just followed the tutorial and tried to download the IDFA extension, but the progress stopped on extracting airpackage. (It's been over 30 minutes). Do I miss anything to unzip it? Below is the log:
`E::LoadUserSettingsProcess::File doesn't exist
⣾ Finding package : com.distriqt.IDFA@latest
✓ Found package: com.distriqt.IDFA@5.0.31
⣽ Finding package : com.distriqt.Core@6.4.3
✓ Found package: com.distriqt.Core@6.4.3
⣻ Finding package : androidx.core@1.3.2
✓ Found package: androidx.core@1.3.2
⢿ Finding package : com.distriqt.playservices.AdsIdentifier@17.0.0
✓ Found package: com.distriqt.playservices.AdsIdentifier@17.0.0
⡿ Finding package : com.distriqt.playservices.Base@17.5.1
✓ Found package: com.distriqt.playservices.Base@17.5.1
Installing package : com.distriqt.playservices.AdsIdentifier@17.0.0
Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
5% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
16% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
21% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
32% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
37% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
43% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
48% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
54% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
59% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
65% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
75% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
81% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
86% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
100% Downloading package : com.distriqt.playservices.AdsIdentifier@17.0.0
✓ downloaded
⣟ extracting F:\TestAPMProj\apm_packages\com.distriqt.playservices.AdsIdentifier\com.distrqt.playservices.AdsIdentifier_17.0.0.airpackage
`

p.s. This is the second time that I run the `install` command. The first time it threw me the error log saying checksum does not match. Here's the log
`
100% Downloading package : com.distriqt.IDFA@5.0.31
✗ Downloaded file failed checks - retry install again later! checksum does not match
ERROR :: Failed to install package : com.distriqt.IDFA@5.0.31
install :: Downloaded file failed checks: checksum does not match
`

**Comment by marchbold** [comment]
Is this still in the git bash client?

**Comment by jimmymjing** [comment]
Oh, yes. I didn't realize it is a client program related issue.

**Comment by marchbold** [comment]
That's my initial thought, as I said, we haven't tested this in the WSL/MinGW/Cygwin environments yet so would expect unusual results. 

Currently I'd suggest you install windows terminal and run either cmd or powershell through that.  

I will have a quick look at this now though, (I'm working on apm at the moment)

**Comment by marchbold** [comment]
Hmmm is working for me in git bash on windows 10. 

Could you run it with debug logging and post the output:

```
apm -l d install
```

**Comment by jimmymjing** [comment]
Here's the output:
`
$ apm -l d install
D::RunConfig::loadEnvironment()
D::LoadWindowsEnvironmentVariablesProcess::start()
D::LoadWindowsEnvironmentVariablesProcess::Process exited with: 0
D::LoadWindowsJavaHomeProcess::start()
D::LoadProjectDefinitionProcess::start()
D::LoadProjectDefinitionProcess::found project file - loading ...
D::LoadUserSettingsProcess::start()
E::LoadUserSettingsProcess::File doesn't exist
E::LoadUserSettingsProcess::Error: File doesn't exist
        at com.apm.data.user::UserSettings/load()
        at com.apm.client.config.processes::LoadUserSettingsProcess/start()
        at com.apm.client.processes::ProcessQueue/checkAndStartNextProcess()
        at com.apm.client.processes::ProcessQueue/process_eventHandler()
        at flash.events::EventDispatcher/dispatchEventFunction()
        at flash.events::EventDispatcher/dispatchEvent()
        at com.apm.client.processes::ProcessBase/complete()
        at com.apm.client.config.processes::LoadProjectDefinitionProcess/start()
        at com.apm.client.processes::ProcessQueue/checkAndStartNextProcess()
        at com.apm.client.processes::ProcessQueue/process_eventHandler()
        at flash.events::EventDispatcher/dispatchEventFunction()
        at flash.events::EventDispatcher/dispatchEvent()
        at com.apm.client.processes::ProcessBase/complete()
        at com.apm.client.config.processes::LoadWindowsJavaHomeProcess/start()
        at com.apm.client.processes::ProcessQueue/checkAndStartNextProcess()
        at com.apm.client.processes::ProcessQueue/process_eventHandler()
        at flash.events::EventDispatcher/dispatchEventFunction()
        at flash.events::EventDispatcher/dispatchEvent()
        at com.apm.client.processes::ProcessBase/complete()
        at com.apm.client.config.processes::LoadWindowsEnvironmentVariablesProcess/onExit()
D::CheckNetworkProcess::start()
D::InstallFinaliseProcess::start()

`

**Comment by jimmymjing** [comment]
Here's the output. It's quite long so I posted it on codepile.
https://www.codepile.net/pile/3nM9qOnd

**Comment by marchbold** [comment]
Oh right, looks as though the powershell command doesn't exist on your machine. 

Could you tell me the output from the following:

```
powershell -command "Get-Host | Select-Object Version"
```

**Comment by jimmymjing** [comment]
It tells me the powershell command doesn't exist...
`$ powershell -command "Get-Host | Select-Object Version"
bash: powershell: command not found
`

**Comment by marchbold** [comment]
What if you provide the full path:

```
/c/windows/system32/windowspowershell/v1.0/powershell -command Get-Host
```

**Comment by jimmymjing** [comment]
It works with full path.

`$ /c/windows/system32/windowspowershell/v1.0/powershell -command Get-Host


Name             : ConsoleHost
Version          : 2.0
InstanceId       : fed2fb00-ceb1-4c3e-ab65-31afcf581ec6
UI               : System.Management.Automation.Internal.Host.InternalHostUserI
                   nterface
CurrentCulture   : zh-CN
CurrentUICulture : zh-CN
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
`

**Comment by marchbold** [comment]
Right, yeah very old version of powershell... What version of Windows are you on? I thought v3.0 was default installed on windows since windows 8...

**Comment by jimmymjing** [comment]
I'm on Windows 7... Is there a way to upgrade the powershell on this machine?
'

**Comment by marchbold** [comment]
Hi, There should be, you'll need v4 or hight, check the following for the links:

https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7.2#upgrading-existing-windows-powershell

I've updated the client to check the powershell version and fallback to an as3 implementation if not available, so you could just try this build for me (still alpha though):

[apm_1.1.0-alpha.zip](https://github.com/airsdk/apm/files/7592490/apm_1.1.0-alpha.zip)

**Comment by jimmymjing** [comment]
I just updated to this alpha version. And here's the output:
$ apm -l d install com.distriqt.IDFA
D::RunConfig::loadEnvironment()
D::LoadWindowsEnvironmentVariablesProcess::start()
D::LoadWindowsEnvironmentVariablesProcess::onClose: (standardOutputClose)[Event type="standardOutputClose" bubbles=false cancelable=false eventPhase=2]
D::LoadWindowsEnvironmentVariablesProcess::onClose: (standardErrorClose)[Event type="standardErrorClose" bubbles=false cancelable=false eventPhase=2]
D::LoadWindowsEnvironmentVariablesProcess::Process exited with: 0
D::LoadWindowsPowershellVersionProcess::start()

**Comment by marchbold** [comment]
Does it stop there?

**Comment by marchbold** [comment]
Maybe try this, could have been a rogue character in that process:

[apm_1.1.1-alpha.zip](https://github.com/airsdk/apm/files/7592585/apm_1.1.1-alpha.zip)

**Comment by jimmymjing** [comment]
I just updated to 1.1.1, and still stop at `D::LoadWindowsPowershellVersionProcess::start()`

**Comment by marchbold** [comment]
Which version of AIR are you using? Any chance you haven't updated to the latest? There was a critical fix for a similar issue in the latest release.

**Comment by jimmymjing** [comment]
I'm using the latest AIR 33.1.1.686. I have upgraded WMF to 5.1 and rebooted my computer. And now it works! Thanks so much!
