### ISSUE TITLE
apm config set throws "ERROR: No output file specified"

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#85]
Hi, I'm trying to set github token by call `apm config set github_token ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXX` but getting the error message: ERROR: No output file specified.

**Comment by marchbold** [comment]
I believe this has been resolved in the current alpha: 

[apm_1.1.1-alpha.zip](https://github.com/airsdk/apm/files/7615776/apm_1.1.1-alpha.zip)

**Comment by jimmymjing** [comment]
Cool! Thanks! I was in 1.1.0-alpha and did run `apm update apm` though.

**Comment by marchbold** [comment]
Yeah this isn't released yet... planning on getting it out later this week.
