### ISSUE TITLE
AndroidManifest.xml and InfoAdditions.xml not merged into final description file

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#86]
Hi, I just followed the post "Migrating to the AIR Package Manager" and setup 2 additional description files (AndroidManifest.xml and InfoAdditions.xml), but I find the content is not getting merged into my final description file. Do I need to set the relative path for these 2 files?

p.s.
When I execute the cmd `apm generate app-descriptor`, I didn't see the output like `Merging with supplied main manifest: config/android/AndroidManifest.xml`

**Comment by marchbold** [comment]
Where have you placed these files? They should be in the directories `config/android/` and `config/ios/` relative to your `project.apm`

**Comment by jimmymjing** [comment]
Oh...I didn't put them into separate ios/android folders. Now it works!
