### ISSUE TITLE
cannot add addtional values to the array for the key CFBundleURLSchemes

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#89]
Hi, I would like to add additional string values for the key `CFBundleURLSchemes` in the infoAddtions section. I added my additional strings in the InfoAdditions.xml and then generated the description file which looks like this:
```xml
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>this_is_the_one_I_inserted</string>
    </array>
  </dict>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>fbxxxxxxxxxxxxxxxx</string>
    </array>
  </dict>
</array>
```
Is it correct or these 2 strings should be combined into the same array? Thanks!
p.s. the FB part is auto generated as I'm using the FB ane.

**Comment by marchbold** [comment]
I believe that is the correct format. 

I assume you are have a `<key>CFBundleURLTypes</key>` entry just before the `<array>` ?

**Comment by marchbold** [comment]
Might double check that though, as I haven't tested an app like this yet. Let me know if it works ?

**Comment by jimmymjing** [comment]
Now the key `CFBundleURLSchemes` gets duplicated in the description xml. Is it possible to insert additional strings into the array? Something like:
```xml
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>this_is_the_one_I_inserted</string>
      <string>fbxxxxxxxxxxxxxxxx</string>
    </array>
</array>
```

**Comment by marchbold** [comment]
I think the first format is correct as well, are you having an issue with that format?

**Comment by jimmymjing** [comment]
Thanks. I will check it out!
btw, adding / modifying additional info in the infoAddtions.xml works great and will merge into the final description file. But if I remove keys from the infoAddition.xml, it won't reflect in the final description file.

**Comment by marchbold** [comment]
Can you elaborate on that, removing something from the info additions should be reflected as the info additions is completely regenerated in the generate `app-descriptor` command?

**Comment by jimmymjing** [comment]
Sorry, now removing gets reflected... I don't know why it doesn't update the description file previously.

**Comment by marchbold** [comment]
Maybe something simple like forgot to save the file in the editor you were using?  I've done that myself ;)
