### ISSUE TITLE
aspectRatio and depthAndStencil get removed from description file

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/apm#90]
Hi, I generated the description file but found the aspectRatio was missing from initalWindow section. Is there a way to add it? I need to set it to landscape. Thanks.
I'd also need to set depthAndStencil to true, and set autoOrients value.

**Comment by marchbold** [comment]
Did you set a template for the app descriptor in `config/application-descriptor.xml` ? If you set this file then the app descriptor is completely regenerated from this file each time, rather than reading the output as the template.

**Comment by jimmymjing** [comment]
I just created the application-descriptor.xml file, as follows:
<application xmlns="http://ns.adobe.com/air/application/33.1">
	<versionLabel>0.2.0</versionLabel>
	<initialWindow>
		<aspectRatio>landscape</aspectRatio>
		<autoOrients>false</autoOrients>
		<fullScreen>true</fullScreen>
		<depthAndStencil>true</depthAndStencil>
	</initialWindow>	
</application>

But when I tried to generate the final description file, I was getting the error ⣷ Updating app descriptor
ApplicationDescriptorGenerationProcess::<id> tag not found

**Comment by marchbold** [comment]
Sorry if I wasn't clear, I was saying "don't" use the `config/application-descriptor.xml`.

If you set `depthAndStencil` and `aspectRatio` in your main app xml, they shouldn't be modified.

**Comment by jimmymjing** [comment]
This is really strange... My original app.xml had depthAndStencil and aspectRatio set, and it did get removed... the original XML also had com.distriqt.Memory in the extensions section which also got removed.

**Comment by marchbold** [comment]
Hmm, something sounds amiss there. Extensions should never get removed. At a guess there may have been a format issue in your original xml that caused an issue? Do you have access to the original xml, could you send it to me for testing at all?

Is it working now?

**Comment by jimmymjing** [comment]
Yes. I can send the original xml to you. What could be the best way to deliver the file to you then?

**Comment by marchbold** [comment]
Perfect thanks, I'll have a look at it.

**Comment by marchbold** [comment]
Everything looks okay with it, ran it through apm here and no issues. Format seems okay .

Not sure what could have happened. 

How are you running the generate command? Are you specifying the output to this file directly? 

eg 

```
apm generate app-descriptor src/aaa-app.xml
```

**Comment by jimmymjing** [comment]
yes. That's exactly the command that I executed

**Comment by jimmymjing** [comment]
I just manually added back the missing things into the description file, and now it works as expected.

**Comment by marchbold** [comment]
Was there a chance that you had a `config/application-descriptor.xml` file when you ran it the first time? That's the only thing I can think of that would cause this behaviour.

**Comment by jimmymjing** [comment]
I'm pretty sure there's no such file. Anyways, something weird happened. I will keep my eyes on it and report it if it happens again.

**Comment by marchbold** [comment]
Okay great, let me know if you figure out how to replicate it.
